### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fluffy-critter** [torcado194/scritch-player#1]
I'd be very interested in using the Scritch player with [pyBlamscamp](https://github.com/fluffy-critter/pyBlamscamp) as it seems way better than the [Blamscamp](https://github.com/blackle/blamscamp) player I've based pyBlamscamp's off of (and which is really the only connection between pyBlamscamp and Blamscamp at this point). There's no license provided on the Scritch player, though, so I'm not sure if that would be okay to do.

I *assume* that since the player itself is intended to be modified and uploaded to itch that this would be okay, but I definitely want to make sure first!

**Comment by torcado194** [comment]
Ah, good idea, thank you! I mentioned on the Scritch editor page that "Scritch is 100% free to use/copy/modify/etc.", having a license to reflect that is a good idea.
From the looks of it, it seems that the MIT license is the most permissive, so I'll go with that for now (adding to the readme). Let me know if there are any other suggestions for a license!

**Comment by fluffy-critter** [comment]
MIT is very permissive, public domain/cc0 is slightly more permissive. :) But both are totally fine.

The general practice is to put it as a file called `LICENSE` in the root directory of the repository, which allows GitHub and a bunch of other tools to detect it automatically.

**Comment by torcado194** [comment]
Ok, good idea. I did see that, just hesitant about cluttering up the directory (the primary goal is to be as approachable as possible to non-tech savvy people). But if you think those benefits outweigh that, ill consider it

**Comment by fluffy-critter** [comment]
Yeah I'd err on the side of a separate file, since that's the general convention and it's not like having an extra text file will hurt anything (just as there's nothing harmful about leaving the README.md around either).

If anything this would be a good reason to move everything (player, media, fonts, etc.) inside a single subdirectory. But regardless, a frontend tool like the online scritch editor or pyBlamscamp would make this easier too. :)

**Comment by torcado194** [comment]
Well, if I could get away with no README either, I would haha.

But ok, the license has been moved to LICENSE.md
