### ISSUE TITLE
Filenames ending in a period confuse itch (or the player?)

### ISSUE THREAD

**Issue by rjp** [torcado194/scritch-player#2]
I had file named `zimpenfish - RecordedAmbientScapesV1 - 10 The Robots Arrived. With War..mp3` which showed up on the player page with a warning triangle instead of the spinny circle.  Same with `zimpenfish - RecordedAmbientScapesV1 - 11 Stuck. Push. Stuck. Push. Plane..mp3`.  Renaming them to remove the double period (cf `zimpenfish - RecordedAmbientScapesV1 - 11 Stuck. Push. Stuck. Push. Plane.mp3`) made everything happy again.

Dunno if this is a scritch, itch, safari, etc. problem but maybe worth flagging up in the scritch builder either way?

**Comment by torcado194** [comment]
Hm, strange! I can't seem to reproduce this, either in the editor or the player.
Was this just in the Scritch player? Did you use the Scritch editor to create the player, and if so was the error present in the preview or just the output?
Also, can you check the browser's console for any errors? 
It's definitely possible it's a safari issue

**Comment by rjp** [comment]
Used the editor - file is ok in the preview.

When uploaded to itch and the page created, I get 'Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object' and a 403 from hwcdn.net for that file.  Also breaks in my local Chrome (97.0.4692.99).

Without the double period, it's fine.

Broken version up at https://zimpenfish.itch.io/testing, pw: moose

(I bet it's some kind of path filtering access control to block attempted accesses to `..` on the CDN; in which case there's nothing Scritch can do about it except maybe flag up a warning when files are uploaded. Changing the filename in the Scritch editor is sufficient to fix the problem.)

**Comment by torcado194** [comment]
Oh, I see! Thank you for this demo. I actually think this is an issue with itch.io and how they are serving their files. (Hosting the files locally or on a different server works fine). I may file an issue about this on their end.
But yes, not something I can fix on Scritch's side besides showing a warning! I may look into that in the future if this isn't resolved by itch :)
