### ISSUE TITLE
Toggle setting to hide/show lyrics overlay on cover art

### ISSUE THREAD

**Issue by lexfeathers** [torcado194/scritch-player#4]
I love how the audio files can have the lyrics attached, though I find it tricky with how they automatically display the media info overtop the cover art by default, obscuring the cover art if you have lyrics added.

It would be really nice if there was a way to only show the mediaInfoContainer div if the info toggle/drawer is currently active on a track. 

The current workaround for this is to add the following to customCSS, though it doesn't allow the functionality of hiding/showing the cover art overlay when the info button gets toggled:

```
#mediaInfoContainer {
  display: none!important;
}
```

**Comment by torcado194** [comment]
The "none" infoStyle hides any text on the cover art but still allows you to see the text by opening the info drawer for the track, in case that works for you. But I think that's a nice idea and is easy enough to implement. I've added a new "overlaid-toggle" infoStyle, let me know if that works as you're expecting :)

**Comment by lexfeathers** [comment]
That's fantastic, exactly what I was imagining! Thanks so much :)
